### ISSUE TITLE
The JIRA key is duplicated when already in place with colon

### ISSUE THREAD

**Issue by krejcit** [dmitry-mashkov/prefix-commit-jira-id#3]
When I manually entered the JIRA key with colon the package added another JIRA key as per below:
`WUNDEN-488: WUNDEN-488:`

This shouldn't happen as the JIRA key was duplicated.

How to replicate:
1. Do some changes in the repository
2. Enter JIRA key with colon at the beginning of commit message
3. Commit

**Comment by krejcit** [comment]
Looks like the package doesn't care about the colon at all. It duplicates the JIRA key.

**Comment by dmitry-mashkov** [comment]
PR opened: https://github.com/dmitry-mashkov/prefix-commit-jira-id/pull/4
